In [3]:
import pandas as pd
import numpy as np

In [4]:
a1=np.arange(6)
a2=a1[np.newaxis,:]
a2.shape

(1, 6)

In [5]:
#creating 1d array using numpy 
a1=np.array([1,2,3,4,5,6])
a1

array([1, 2, 3, 4, 5, 6])

In [6]:
#creating 2d array using numpy
a2=np.array([[1,2,3],[4,5,6],[7,8,9]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
print(a2[0])

[1 2 3]


In [8]:
#zeros array
np.zeros(4)

array([0., 0., 0., 0.])

In [9]:
#creating an array with 2 element
np.empty(2)

array([-1.25583192e-67,  7.45727421e+08])

In [10]:
np.arange(4)

array([0, 1, 2, 3])

In [11]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

# .linspace()-

to create an array with values that are spaced linearly specified interval

In [12]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [13]:
x=np.ones(2,dtype=np.int64)
x

array([1, 1], dtype=int64)

# Adding Removing and Sorting Elements

np.sort() -- sorting an element is simple with np.sort

np.concatenate() -- adding two lists

In [14]:
arr=np.array([2,1,5,8,6,4,9,3,5])
arr

array([2, 1, 5, 8, 6, 4, 9, 3, 5])

In [15]:
np.sort(arr)

array([1, 2, 3, 4, 5, 5, 6, 8, 9])

In [16]:
a=([1,2,3,4])
b=([5,6,7,8])

In [17]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
a1=np.array([[9,8,4],[7,6,2]])
a2=np.array([[5,4,1]])

In [19]:
np.concatenate((a1,a2),axis=0)

array([[9, 8, 4],
       [7, 6, 2],
       [5, 4, 1]])

# Shape and Size of Array

In [20]:
array=np.array([[[0,1,2,3,],
           [4,5,6,7],
           
           [0,1,2,3],
           [4,5,6,7],
                 
           [0,1,2,3],
           [4,5,6,7]]])


In [21]:
array.ndim

3

In [22]:
array.size

24

In [23]:
array.shape

(1, 6, 4)

# Reshape an Array

In [24]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [25]:
b=a.reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [26]:
b=a.reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [27]:
np.reshape(a,newshape=(1,6),order='c')

array([[0, 1, 2, 3, 4, 5]])

# Convert 1D Array Into 2D Array And How To Add .newaxis To An Memory

In [28]:
a=np.array([1,2,3,4,5,6])
a.shape

(6,)

In [29]:
#np.newaxis to add a new axis
a1=a[np.newaxis, :]
a1.shape

(1, 6)

In [30]:
row_vector=a[np.newaxis,:]
row_vector.shape

(1, 6)

In [31]:
col_vector=a[:,np.newaxis]
col_vector.shape

(6, 1)

In [32]:
a=np.array([1,2,3,4,5,6])
a.shape

(6,)

In [33]:
b=np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [34]:
b=np.expand_dims(a,axis=0)
b.shape

(1, 6)

# Indexing And Slicing

In [35]:
data=np.array([1,2,3])


In [36]:
data[1]

2

In [37]:
data[0:2]

array([1, 2])

In [38]:
data[-1]

3

In [39]:
data[:]

array([1, 2, 3])

In [40]:
data[-2:]

array([2, 3])

In [41]:
data[1:]

array([2, 3])

In [42]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,8,7,6]])

In [43]:
print(a[a<5])

[1 2 3 4]


In [44]:
five_up=(a>=5)
print(a[five_up])

[5 6 7 8 9 8 7 6]


In [45]:
divisible_by_2=a[a%2==0]
print(divisible_by_2)

[2 4 6 8 8 6]


In [46]:
#satisfy two conditions using the & and | operator
c=a[(a>2)&(a<11)]
c

array([3, 4, 5, 6, 7, 8, 9, 8, 7, 6])

In [47]:
five_up=(a>5) | (a==5)
five_up

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [48]:
b=np.nonzero(a<5)
b

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))

In [49]:
list_of_cordinates=list(zip(b[0],b[1]))
for coord in list_of_cordinates:
    print(list_of_cordinates)

[(0, 0), (0, 1), (0, 2), (0, 3)]
[(0, 0), (0, 1), (0, 2), (0, 3)]
[(0, 0), (0, 1), (0, 2), (0, 3)]
[(0, 0), (0, 1), (0, 2), (0, 3)]


In [50]:
print(a[b])

[1 2 3 4]


In [51]:
not_there=np.nonzero(a==42)

In [52]:
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


# Basic Array Operations

In [53]:
import numpy as np
data=np.array([1,2])
ones=np.ones(2,dtype=int)
data+ones

array([2, 3])

In [54]:
data-ones

array([0, 1])

In [55]:
data*ones

array([1, 2])

In [56]:
data/ones

array([1., 2.])

In [57]:
# sum of elements
a=np.array([1,2,3,4,5])
a.sum()

15

In [58]:
# 2D array
b=np.array([[1,2],[3,5]])
sum(b)

array([4, 7])

In [59]:
b.sum(axis=0)

array([4, 7])

In [60]:
b.sum(axis=1)

array([3, 8])

In [61]:
a.max()

5

In [62]:
a.min()

1

In [63]:
a=np.array([[0.1234,0.5678,0.9876],[0.4567,0.8907,0.2345]])
print(a.sum())
print(a.max())
print(a.min())

3.2607000000000004
0.9876
0.1234


In [64]:
a.min(axis=0)

array([0.1234, 0.5678, 0.2345])

# Broadcasting

Numpy understand that the multiplactin happen with each cell.that concept is called broadcasting

In [65]:
data=np.array([1,2,3,4])
data*4

array([ 4,  8, 12, 16])

# Creating Metrices

In [66]:
data=np.array([[1,2],[3,4],[5,6],[7,8],[9,8]])
data

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 8]])

# Indexing Slicing

In [67]:
data[0,1]

2

In [68]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [69]:
data[0:2,0]

array([1, 3])

# Aggregate functions ---> min(),max(),sum()

In [70]:
data.max(axis=0)

array([9, 8])

In [71]:
data.min(axis=1)

array([1, 3, 5, 7, 8])

In [72]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [73]:
np.ones(3)

array([1., 1., 1.])

In [74]:
np.zeros(3)

array([0., 0., 0.])

# Generating Random Numbers

In [75]:
rng=np.random.default_rng()
rng.random(3)

array([0.68036521, 0.90454963, 0.35634166])

In [76]:
rng.integers(5,size=(2,4))
a

array([[0.1234, 0.5678, 0.9876],
       [0.4567, 0.8907, 0.2345]])

# Get Unique items And Count

In [77]:
import numpy as np
a=np.array([1,2,3,4,5,6,1,2,3])
a

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

In [78]:
unique_values=np.unique(a)
unique_values

array([1, 2, 3, 4, 5, 6])

In [79]:
unique_values,indices_list=np.unique(a,return_counts=True)
unique_values
indices_list

array([2, 2, 2, 1, 1, 1], dtype=int64)

In [80]:
unique_values,occurrence_count=np.unique(a,return_counts=True)
print(occurrence_count)

[2 2 2 1 1 1]


In [81]:
a_2d=np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
a_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [82]:
unique_values=np.unique(a_2d)
unique_values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [83]:
unique_rows=np.unique(a_2d,axis=0)
unique_rows

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [84]:
unique_rows,indices,occurrence_count=np.unique(a_2d,axis=0,return_counts=True,return_index=True)

In [85]:
print(indices)

[0 1 2]


In [86]:
print(occurrence_count)

[2 1 1]


# Transposing And Reshaping Array

In [87]:
data.reshape(5,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 8]])

In [88]:
data.reshape(2,5)

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 8]])

In [92]:
import numpy as np
arr=np.arange(6).reshape((2,3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [97]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [100]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

# Reverse An Array

In [101]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [103]:
Reversed_arr=np.flip(arr)
Reversed_arr

array([5, 4, 3, 2, 1])

In [104]:
arr_2d=([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [106]:
reversed_arr_2d=np.flip(arr_2d)
reversed_arr_2d

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [108]:
reversed_arr_rows=np.flip(arr_2d,axis=0)
reversed_arr_rows

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [110]:
reversed_arr_columns=np.flip(arr_2d,axis=1)
reversed_arr_columns

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [113]:
arr_2d[1]=(arr_2d[1])
arr_2d[1]

array([6, 5, 4])

In [119]:
arr_2d[:1]=np.flip(arr_2d[1:])
arr_2d[:1]

[array([9, 8, 7])]

# Reshaping And Flattening Multidimensional Arrays

In [121]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [147]:
# Flatten --- changes to your new array won’t change the parent array

In [148]:
x.flatten()

array([90,  2,  3,  4,  5,  6,  7,  8,  9])

In [149]:
a1=x.flatten()
a1[0]=90

In [150]:
print(x)

[[90  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [151]:
print(a1)

[90  2  3  4  5  6  7  8  9]


In [152]:
b1=x.flatten()
b1[1]=80

In [153]:
print(b1)

[90 80  3  4  5  6  7  8  9]


In [155]:
# Ravel ---  the changes you make to the new array will a ect the parent array

In [156]:
 a2 = x.ravel()
 a2[0] = 98

In [157]:
print(x)

[[98  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [158]:
b1 = x.ravel()
a2[0]=90

In [159]:
b1

array([90,  2,  3,  4,  5,  6,  7,  8,  9])

In [160]:
x

array([[90,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

# Access Docstring

In [161]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [162]:
help(print)

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.
    
    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.



In [163]:
a = np.array([1, 2, 3, 4, 5, 6])

In [164]:
a?

Type:        ndarray
String form: [1 2 3 4 5 6]
Length:      6
File:        c:\users\91901\.opera\lib\site-packages\numpy\__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any object tha

In [165]:
def double(a):
    return a*2

In [167]:
double?

Signature: double(a)
Docstring: <no docstring>
File:      c:\users\91901\appdata\local\temp\ipykernel_2548\2157672883.py
Type:      function

In [170]:
# Using a double question mark ( ?? ) allows you to access the source code.

In [171]:
double??

Signature: double(a)
Docstring: <no docstring>
Source:   
def double(a):
    return a*2
File:      c:\users\91901\appdata\local\temp\ipykernel_2548\2157672883.py
Type:      function

In [172]:
len?

Signature: len(obj, /)
Docstring: Return the number of items in a container.
Type:      builtin_function_or_method

In [173]:
len??

Signature: len(obj, /)
Docstring: Return the number of items in a container.
Type:      builtin_function_or_method

# Save And Load Numpy Objects

In [176]:
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [177]:
np.save('filename',a)

In [179]:
b=np.load('filename.npy')

In [180]:
print(a)

[1 2 3 4 5 6]


In [181]:
print(b)

[1 2 3 4 5 6]


In [182]:
a1=np.array([12,3,45,6,4])
a1

array([12,  3, 45,  6,  4])

In [183]:
np.save('filename',a1)

In [184]:
np.load('filename.npy')

array([12,  3, 45,  6,  4])

In [185]:
csv_arr=([9,8,7,6,5,4])
csv_arr

[9, 8, 7, 6, 5, 4]

In [186]:
np.savetxt=('new_csv_txt',csv_arr)

In [187]:
np.loadtxt=('new_csv_txt',csv_arr)

In [188]:
csv_arr

[9, 8, 7, 6, 5, 4]

# Importing And Exporting CSV

In [190]:
import pandas as pd

In [197]:
pd.read_csv('Downloads\IMDB Dataset.csv')

review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [203]:
df=pd.DataFrame(a)

In [204]:
df

0
0  1
1  2
2  3
3  4
4  5
5  6

In [205]:
df.to_csv('pd.csv')

In [207]:
data=pd.read.csv('pd.csv')

AttributeError: module 'pandas' has no attribute 'read'