# creating numpy array

In [2]:
import numpy as np

In [3]:
np.array([1,2,3,4])    #1d array

array([1, 2, 3, 4])

In [5]:
a=np.array([1,2,3,4])   #vector
a

array([1, 2, 3, 4])

In [6]:
type(a)

numpy.ndarray

In [9]:
#2d array
new=np.array([[1,2,3,4],[5,6,7,8]])
new

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
#3d array
np.array([[1,2,3,4],[5,6,7,8],[9,8,7,6],[5,4,3,2]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 8, 7, 6],
       [5, 4, 3, 2]])

# dtype

the desired data type for the array if not given then the type will be determined as the minimum type required to hold the objects in the sequence

In [12]:
np.array([23,34,12],dtype=float)

array([23., 34., 12.])

In [13]:
np.array([23,12,23],dtype=bool)     #here true because,python treats non zero

array([ True,  True,  True])

In [15]:
np.array([12,23,23],dtype=complex)

array([12.+0.j, 23.+0.j, 23.+0.j])

# Numpy Arrays vs python sequences

NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). 
Changing the size of an ndarray will create a new array and delete the original. 

The elements in a NumPy array are all required to be of the same data type, and thus will be 
the same size in memory. 

NumPy arrays facilitate advanced mathematical and other types of operations on large 
numbers of data. Typically, such operations are executed more efficiently and with less code 
than is possible using Python’s built-in sequences. 

A growing plethora of scientific and mathematical Python-based packages are using NumPy 
arrays; though these typically support Python-sequence input, they convert such input to 
NumPy arrays prior to processing, and they often output NumPy arrays.

# arange

arange can be called with a varying number of positional argument

In [17]:
np.arange(1,30)    #1 include ,30 last one got exclude

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [19]:
np.arange(1,30,2)     #strides----> alternate number

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

# reshape

both of number products should be equal to number of items present inside the array

In [25]:
np.arange(1,11).reshape(5,2)         #converted 5 rows and 2 columns

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [27]:
np.arange(1,21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

# ones and zeros

you can initlize the values and create values

In [29]:
# np.ones and np.zeros
np.ones((3,4))         #we have to mention inside tuple

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
#another type ----->random

np.random.random((4,3))

array([[0.11490726, 0.6697729 , 0.64676727],
       [0.41719701, 0.84819859, 0.45810973],
       [0.27123303, 0.86933002, 0.09875965],
       [0.10031198, 0.57837523, 0.39821525]])

# linspace

In [2]:
import numpy as np
np.linspace(-10,10,10)          #lower range,upper range,step index

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [3]:
np.linspace(-2,12,6)

array([-2. ,  0.8,  3.6,  6.4,  9.2, 12. ])

# Identity matrix

Identity matrix is that diagonal items will be ones and everything will be zeros

In [4]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# Array Attributes

In [7]:
a1=np.arange(10)   #1d
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a2=np.arange(12,dtype=float).reshape(3,4)     #matrix
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [12]:
a3=np.arange(8,dtype=int).reshape(2,2,2) #3d tensor
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# ndim

to findout given arrays number of dimension

In [13]:
a1.ndim

1

In [14]:
a2.ndim

2

In [15]:
a3.ndim

3

# shape

gives each item consists of no of rows and np. of column

In [17]:
a1.shape   #a1 array has 10 items

(10,)

In [18]:
a2.shape    #a2 has 3 rows and 4 columns

(3, 4)

In [19]:
a3.shape    # 2 says consist of 2d array,a3 has 2 rows and 2 cloumns 

(2, 2, 2)

# size

gives number of items

In [20]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [21]:
a3.size     #it has 8 items , like shape:(2,2,2)

8

In [22]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [23]:
a2.size

12

In [24]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
a1.size

10

# Item Size

Memory occupied by the item

In [26]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
a1.itemsize  #bytes

4

In [28]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [29]:
a2.itemsize     #integer 64 gives=8bytes

8

In [30]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [31]:
a3.itemsize       #integer 32 gives=4bytes

4

In [32]:
# dtype

dtype gives type of item

In [33]:
print(type(a1))
print(type(a2))
print(type(a3))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [35]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


# Changing Data Type

In [38]:
#astype
x=np.array([33,22,2.5])
x

array([33. , 22. ,  2.5])

In [39]:
x.astype(int)

array([33, 22,  2])

# Array Operations

In [40]:
b1=np.arange(12).reshape(3,4)
b2=np.arange(12,24).reshape(3,4)

In [41]:
b1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
b2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Scalar operations

scalar operation on numpy arrays include performing addition or substarction or multiplication on each element of a numpy array

In [44]:
#arithemetic
b1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [45]:
#substraction
b1-2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [46]:
#multiplication
b1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [47]:
#power
b1/2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [48]:
#modulo
b1%2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]], dtype=int32)

In [49]:
#power
b1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])