In [2]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr.dtype)

int32


In [3]:
arr=np.array(["komal","navira","vaishnavi"])
print(arr)

['komal' 'navira' 'vaishnavi']


In [4]:
print(arr.dtype)

<U9


In [7]:
arr=np.array(["komal","navira"],dtype='S')
print(arr)
print(arr.dtype)

[b'komal' b'navira']
|S6


In [8]:
arr=np.array([1.1,2.1,3.1])
newarr=arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [10]:
x=arr.copy()
print(x)

[1.1 2.1 3.1]


In [22]:
arr=([1,2,3,4,5,6,7])
print(arr)

[1, 2, 3, 4, 5, 6, 7]


In [23]:
x=arr.copy()
print(x)

[1, 2, 3, 4, 5, 6, 7]


In [26]:
arr=np.array([1,2,3,4,5])
x=arr.view()
#x[0]=[12]
print(arr)
print(x)

[1 2 3 4 5]
[1 2 3 4 5]


In [30]:
arr=([1,2,3,4])
x=arr.copy()
print(x)
arr[1]=5
print(arr)

[1, 2, 3, 4]
[1, 5, 3, 4]


In [4]:
import numpy as np
arr=np.array([[1,2,3,6],[4,5,6,8]])
print(arr.shape)

(2, 4)


In [6]:
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print("shape of array:",arr.shape)

[[[[[1 2 3 4]]]]]
shape of array: (1, 1, 1, 1, 4)


In [9]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.reshape(4,3))
newarr=arr.reshape
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
<built-in method reshape of numpy.ndarray object at 0x000001FD5DB2E070>


In [13]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.reshape(2,3,2))
newarr=arr.reshape
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
<built-in method reshape of numpy.ndarray object at 0x000001FD5DB65B90>


In [17]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr.reshape)
newarr=arr.reshape(3,3)
print(newarr)

<built-in method reshape of numpy.ndarray object at 0x000001FD5DBBA130>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(2,4).base)

[1 2 3 4 5 6 7 8]


In [23]:
arr=np.array([1,2,3,4,5,6,7,8])
newarr=(arr.reshape(2,2,-1))
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [24]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
newarr=arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6 7 8]


In [26]:
#iterating 1D arrays
arr=np.array([1,2,3,4,5,6])
for x in arr:
    print(x)

1
2
3
4
5
6


In [27]:
#iterating 2D arrays
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [28]:
#iterate on each scalar element of the 2D array
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    for y in arr:
        print(y)

[1 2 3]
[4 5 6]
[1 2 3]
[4 5 6]


In [29]:
#iterating 3D arrays
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6],[7,8,9],[6,7,8]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
6
7
8


In [5]:
arr=np.array([[[1,2],[3,4],[6,7],[8,9]]])
for x in np.nditer(arr): #nditer is a function is python numpy library useful for iterating multi-dimensional arrays
    print(x)

1
2
3
4
6
7
8
9


In [14]:
arr=np.array([[[1,2],[3,4],[5,6],[7,8]]])
for x in np.nditer(arr[:,::2]):
    print(x)
    

1
2
5
6


In [15]:
from numpy import random
x=random.randint(100)
print(x)

48


In [17]:
from numpy import random
x=random.rand()
print(x)

0.1315643572563896


In [18]:
#generate 1D array
x=random.randint(100,size=5)
print(x)

[71 61 91  5 66]


In [22]:
#generate 2D array
x=random.randint(200,size=(5,5))
print(x)

[[166 194 172  43 180]
 [178  68  73 118 143]
 [ 28 188   7  64 190]
 [121 108 182 182  47]
 [ 45 137  50 129 160]]


In [23]:
#generate float 1D array
x=random.rand(5)
print(x)

[0.55012608 0.31107153 0.25735787 0.33491104 0.44477318]


In [27]:
#generate float array
x=random.rand(5,3,)
print(x)

[[0.10174471 0.94386295 0.02141803]
 [0.57866776 0.05155627 0.57923157]
 [0.12434595 0.38125372 0.14257661]
 [0.68179952 0.97378275 0.80374498]
 [0.49487898 0.76965126 0.66169209]]


In [29]:
#return 1 values in an array
x=random.choice([1,4,7,9])
print(x)

1


In [32]:
x=random.choice([1,3,5,7,9],size=(3,5))
print(x)

[[7 7 3 7 7]
 [7 3 9 7 9]
 [7 1 9 1 5]]


In [34]:
#random shuffle elemenets from the array
'''shuffle means changing arrangement of elements. shuffle method change the orignal array.'''
arr=np.array([1,2,3,4,5])
random.shuffle(arr)
print(arr)

[5 2 3 1 4]


In [38]:
#random permutation of elements
'''[3,2,1] is a permutation of [1,2,3]'''
arr=np.array([1,2,3,4,5])
print(random.permutation(arr))

[2 1 3 4 5]
